<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <Version>$(Cocos2DMonoVersion)</Version>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE;WINDOWS</DefineConstants>
    <OutputPath>bin\macOS\AnyCPU\Debug\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Icon.ico" />
    <None Remove="Icon.bmp" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Icon.ico" />
    <EmbeddedResource Include="Icon.bmp" />
  </ItemGroup>
  <ItemGroup>
    <TrimmerRootAssembly Include="Microsoft.Xna.Framework.Content.ContentTypeReader" Visible="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Cocos2D-Mono.Core" Version="$(Cocos2DMonoVersion)" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="$(MonoGameVersion)" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Content\fonts\arial.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Content\fonts\arial-16.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Content\fonts\arial-18.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Content\fonts\arial-22.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Content\fonts\arial-64.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>